version: '3.7'

services:
  vaultwarden:
    image: vaultwarden/server:1.25.1
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    networks:
      - tipi_main_network
