version: "3.7"

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.6
    restart: always
    ports:
      - ${NGINX_PORT-80}:80
      - ${PROXY_PORT-8080}:8080
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik:/root/.config
    networks:
      - tipi_main_network

  api:
    image: meienberger/runtipi:rc-${TIPI_VERSION}
    command: bash -c "cd /api && npm run start"
    container_name: api
    ports:
      - 3001:3001
    volumes:
      ## Docker sock
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}:/tipi
    environment:
      - INTERNAL_IP=${INTERNAL_IP}
      - TIPI_VERSION=${TIPI_VERSION}
      - JWT_SECRET=${JWT_SECRET}
      - ROOT_FOLDER_HOST=${ROOT_FOLDER_HOST}
      - NGINX_PORT=${NGINX_PORT}
    networks:
      - tipi_main_network

  dashboard:
    image: meienberger/runtipi:rc-${TIPI_VERSION}
    command: bash -c "cd /dashboard && npm run start"
    container_name: dashboard
    ports:
      - 3000:3000
    networks:
      - tipi_main_network
    environment:
      - INTERNAL_IP=${INTERNAL_IP}
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: PathPrefix("/") # Host(`tipi.local`) &&
      traefik.http.routers.dashboard.entrypoints: webinsecure
      traefik.http.routers.dashboard.service: dashboard
      traefik.http.services.dashboard.loadbalancer.server.port: 3000

networks:
  tipi_main_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.enable_icc: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.21.21.0/24
