version: "3.7"
services:
  invidious:
    user: 1000:1000
    container_name: invidious
    image: quay.io/invidious/invidious:latest-arm64
    restart: unless-stopped
    dns:
      - ${DNS_IP}
    ports:
      - "${APP_PORT}:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: tipi
          password: tipi
          host: invidious-db
          port: 5432
        check_tables: true
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db
    networks:
      - tipi_main_network

  invidious-db:
    user: 1000:1000
    container_name: invidious-db
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
      - ${APP_DATA_DIR}/data/init/sql:/config/sql
      - ${APP_DATA_DIR}/data/init/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: tipi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    networks:
      - tipi_main_network
